[package]
name = "dioxus-mobile-plugin-build"
version = { workspace = true }
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Build-script helpers for compiling Dioxus mobile plugins"
repository = "https://github.com/DioxusLabs/dioxus"
homepage = "https://dioxuslabs.com"
documentation = "https://docs.rs/dioxus-mobile-plugin-build"

[dependencies]
