[package]
name = "harness-web-with-default-features"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
dioxus = { workspace = true }


[features]
default=["other"]
other=[]

    