[package]
name = "generational-box"
authors = ["Evan Almloff"]
version = { workspace = true }
edition = "2021"
description = "A box backed by a generational runtime"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
keywords = ["generational", "box", "memory", "allocator"]
rust-version = "1.83.0"

[dependencies]
parking_lot = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
criterion = { workspace = true }

[features]
debug_borrows = []
debug_ownership = []

[[bench]]
name = "lock"
harness = false

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
