[package]
name = "rsx-prelude"
version = "0.1.0"
authors = ["Jonathan Kelley"]
edition = "2021"
description = "Basic functionality for the dioxus rsx macro."
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
documentation = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react", "wasm"]
rust-version = "1.60.0"

[dependencies]
dioxus-core-macro = { path = "../core-macro", version = "^0.2.1" }
dioxus-core = { path = "../core", version = "^0.2.1" }
dioxus-html = { path = "../html", version = "^0.2.1" }
dioxus-rsx-interpreter = { path = "../rsx_interpreter", version = "^0.1.0", optional = true }
dioxus-hooks = { path = "../hooks", version = "^0.2.1" }

[features]
hot_reload = ["dioxus-core-macro/hot_reload", "dioxus-rsx-interpreter"]
