#:schema ../../../packages/cli/schema2.json

[bundle]
identifier = "com.dioxuslabs.geolocation"
publisher = "Dioxus Labs"

[ios]
deployment_target = "15.0"
background_modes = ["location"]

[android]
min_sdk = 24
target_sdk = 34
features = ["android.hardware.location.gps"]

[permissions]
location = { precision = "fine", description = "Access your precise location to provide location-based services" }
