#:schema ../../../packages/cli/cli-schema.json

[bundle]
identifier = "com.dioxuslabs.geolocation"
publisher = "Dioxus Labs"

[permissions]
location = { precision = "fine", description = "Access your precise location to provide location-based services" }
bluetooth = { description = "Need to access your bluetooth" }
calendar = { description = "Need to access your calendar!" }

[ios]
deployment_target = "15.0"
background_modes = ["location"]

[android]
min_sdk = 24
target_sdk = 34
features = ["android.hardware.location.gps"]
