[package]
name = "dioxus-core-macro"
version = { workspace = true }
authors = ["Jonathan Kelley"]
edition = "2021"
description = "Core macro for Dioxus Virtual DOM"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0" }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits", "visit"] }
dioxus-rsx = { workspace = true }
convert_case = { workspace = true }

# testing
[dev-dependencies]
dioxus = { workspace = true }
dioxus-html = { workspace = true, features = ["serialize"]}
rustversion = "1.0"
tokio = { workspace = true, features = ["full", "time"] }
trybuild = "1.0"

[features]
default = []

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
