[package]
name = "dioxus-cli-config"
version = { workspace = true }
authors = ["Jonathan Kelley"]
edition = "2021"
description = "Configuration for the Dioxus CLI"
repository = "https://github.com/DioxusLabs/dioxus/"
license = "MIT OR Apache-2.0"
keywords = ["react", "gui", "cli", "dioxus", "wasm"]

[dependencies]
clap = { version = "4.2", features = ["derive"], optional = true }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
toml = { workspace = true, optional = true }
cargo_toml = { workspace = true, optional = true }
once_cell = "1.18.0"
tracing = { workspace = true }

# bundling
tauri-bundler = { workspace = true, optional = true }
tauri-utils = { workspace = true, optional = true }

dirs = { workspace = true, optional = true }

[build-dependencies]
built = { version = "=0.7.3", features = ["git2"] }

[features]
default = ["read-config"]
cli = ["dep:tauri-bundler", "dep:tauri-utils", "read-from-args", "dep:toml", "dep:cargo_toml", "dep:dirs"]
read-config = []
read-from-args = ["dep:clap"]

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
