[package]
name = "bevy-example"
version = "0.0.0"
edition = "2021"
license = "MIT"
publish = false

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
native = ["dioxus/native"]
tracing = ["dep:tracing-subscriber", "dioxus-native/tracing"]

[dependencies]
bevy = { version = "0.16" }
dioxus-native = { workspace = true }
dioxus = { workspace = true }
wgpu = { workspace = true }
color = "0.3"
tracing-subscriber = { workspace = true, optional = true }
