[package]
name = "fullstack-auth-example"
version = "0.1.0"
edition = "2021"
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-web = { workspace = true, features = ["hydrate"], optional = true }
dioxus = { features = ["fullstack"], workspace = true }
axum = { workspace = true, optional = true, features = ["macros"]}
tokio = { workspace = true, features = ["full"], optional = true }
tower-http = { workspace = true, features = ["auth"], optional = true }
async-trait = { version = "0.1.88", optional = true }
sqlx = { version = "0.8.6", features = [
    "macros",
    "migrate",
    "postgres",
    "sqlite",
    "_unstable-all-types",
    "tls-native-tls",
    "runtime-tokio",
], optional = true }
http = { workspace = true, optional = true }
tower = { workspace = true, optional = true }

execute = "0.2.13"
serde = { workspace = true }
anyhow = { workspace = true }

[dependencies.axum_session]
workspace = true
optional = true

[dependencies.axum_session_auth]
workspace = true
optional = true

[dependencies.axum_session_sqlx]
workspace = true
features = ["sqlite"]
optional = true

[features]
default = ["web", "server"]
server = [
    "dioxus/server",
    "dep:axum",
    "dep:tokio",
    "dep:tower-http",
    "dep:async-trait",
    "dep:sqlx",
    "dep:axum_session",
    "dep:axum_session_auth",
    "dep:axum_session_sqlx",
    "dep:http",
    "dep:tower",
]
web = ["dioxus/web", "dep:dioxus-web"]
