[package]
name = "dioxus-native"
version = "0.0.0"
license.workspace = true
edition = "2021"

[features]
default = ["accessibility", "hot-reload", "menu", "tracing"]
accessibility = ["blitz-shell/accessibility"]
menu = ["blitz-shell/menu"]
tracing = ["dep:tracing", "blitz-shell/tracing"]
hot-reload = ["dep:dioxus-cli-config", "dep:dioxus-devtools"]

[dependencies]
# Blitz dependencies
blitz-renderer-vello = { path = "../blitz-renderer-vello" }
blitz-dom = { path = "../blitz-dom" }
blitz-net = { path = "../blitz-net" }
blitz-traits = { path = "../blitz-traits" }
blitz-shell = { path = "../blitz-shell" }

# DioxusLabs dependencies
dioxus = { workspace = true }
dioxus-cli-config = { workspace = true, optional = true }
dioxus-devtools = { workspace = true, optional = true }

# Windowing & Input
winit = { workspace = true }
keyboard-types = { workspace = true }

# IO & Networking
tokio = { workspace = true, features = ["full"] }

# Other dependencies
tracing = { workspace = true, optional = true }
rustc-hash = { workspace = true }
futures-util = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
