[package]
name = "fermi"
version = { workspace = true }
authors = ["Jonathan Kelley"]
edition = "2018"
description = "Global state management for Dioxus"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react", "state-management"]



[dependencies]
dioxus-core = { workspace = true }
im-rc = { version = "15.0.0", features = ["serde"] }
tracing = { workspace = true }

[dev-dependencies]
closure = "0.3.0"
