[package]
name = "dioxus-mobile"
version = { workspace = true }
authors = ["Jonathan Kelley"]
edition = "2021"
description = "Mobile-compatible renderer for Dioxus"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com/learn/0.5/getting_started"
keywords = ["dom", "ui", "gui", "react"]
license = "MIT OR Apache-2.0"

[dependencies]
dioxus-desktop = { workspace = true }

[lib]
doctest = false
test = false
# tests suspended until package ready

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
