[package]
name = "rsx-rosetta"
version = { workspace = true }
edition = "2021"
authors = ["Jonathan Kelley"]
description = "Autofomatter for Dioxus RSX"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
documentation = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-autofmt = { workspace = true }
dioxus-rsx = { workspace = true }
dioxus-html = { workspace = true, features = ["html-to-rsx"]}
html_parser = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full"] }
convert_case = "0.5.0"
oxc_parser = "0.12.5"
oxc_allocator = "0.12.5"
oxc_span = "0.12.5"
oxc_ast = {version = "0.12.5", features = ["serialize"]}

# [features]
# default = ["html"]

# eventually more output options

[dev-dependencies]
pretty_assertions = "1.2.1"
serde_json = { workspace = true }
