[package]
name = "dioxus-hooks"
version = "0.3.1"
authors = ["Jonathan Kelley"]
edition = "2018"
description = "Basic useful hooks for Dioxus."
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react"]

[features]
default = []
nightly-features = []

[dependencies]
dioxus-core = { workspace = true }
futures-channel = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
debug-cell = { git = "https://github.com/Niedzwiedzw/debug-cell", rev = "3352a1f8aff19f56f5e3b2018200a3338fd43d2e" } # waiting for the merge / official DioxusLabs fork
slab.workspace = true

[dev-dependencies]
futures-util = { workspace = true, default-features = false }
dioxus-core = { workspace = true }
dioxus = { workspace = true }
web-sys = { version = "0.3.64", features = ["Document", "Window", "Element"] }
