[package]
name = "dioxus-hooks"
version = { workspace = true }
authors = ["Jonathan Kelley"]
edition = "2021"
description = "Basic useful hooks for Dioxus."
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react"]

[features]
default = []
nightly-features = []

[dependencies]
dioxus-core = { workspace = true }
dioxus-signals = { workspace = true }
futures-channel = { workspace = true }
tracing = { workspace = true }
slab = { workspace = true }
futures-util = { workspace = true}
generational-box.workspace = true
rustversion = "1.0.17"

[dev-dependencies]
futures-util = { workspace = true, default-features = false }
dioxus-core = { workspace = true }
dioxus = { workspace = true }
web-sys = { version = "0.3.64", features = ["Document", "Window", "Element"] }
tokio = { version = "1.0", features = ["full"] }
reqwest = { workspace = true }

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
