[package]
name = "dioxus-stores"
version = { workspace = true }
edition = "2021"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com/docs/0.5/guide/en/getting_started/fullstack.html"
keywords = ["dom", "ui", "gui", "react", "liveview"]
authors = ["Jonathan Kelley", "Evan Almloff"]
license = "MIT OR Apache-2.0"
description = "Server function macros for Dioxus"

[dependencies]
dioxus-core = { workspace = true }
dioxus-signals = { workspace = true }
dioxus-stores-macro = { workspace = true, optional = true }
generational-box.workspace = true

[dev-dependencies]
dioxus = { workspace = true }

[features]
default = ["macro"]
macro = ["dep:dioxus-stores-macro"]
large-path = []

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
