[package]
name = "const-serialize-macro"
version = "0.8.0-alpha.0"
authors = ["Evan Almloff"]
edition = "2021"
description = "A macro to derive const serialize"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dioxuslabs/dioxus"
homepage = "https://dioxuslabs.com/learn/0.5/getting_started"
keywords = ["const", "serialize"]

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[lib]
proc-macro = true
