[package]
name = "manganis-common"
version.workspace = true
edition = "2021"
authors = ["Evan Almloff"]
description = "Ergonomic, automatic, cross crate asset collection and optimization"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/manganis/"
homepage = "https://dioxuslabs.com"
keywords = ["assets"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.183", features = ["derive"] }
anyhow = "1"
base64 = { workspace = true }
infer = { workspace = true }
fluent-uri = { version = "0.2.0", features = ["serde"] }

# tracing = "0.1.40"

# Remote assets
# reqwest = { version = "0.12.5", features = ["blocking"] }
# http = "1.1.0"
# http-serde = "2.1.1"

[features]
default = ["html"]
html = []

[build-dependencies]
built = { version = "0.7", features = ["git2"] }
scratch = "1.0.7"
