[package]
name = "dioxus-fullstack-core"
authors = ["Jonathan Kelley", "Evan Almloff"]
version = { workspace = true }
edition = "2021"
description = "Hooks for serializing futures, values in dioxus-fullstack and other utilities"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["web", "gui", "server"]
resolver = "2"

[dependencies]
dioxus-core = { workspace = true, features = ["serialize"]}
dioxus-signals = { workspace = true }
dioxus-hooks = { workspace = true }
futures-channel = { workspace = true }
serde = { workspace = true }
dioxus-history = { workspace = true }
dioxus-document = { workspace = true }
ciborium = { workspace = true }
base64 = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
axum-core = { workspace = true }
http = { workspace = true }
reqwest = { workspace = true }
tungstenite = { workspace = true }
anyhow = { workspace = true }
inventory = { workspace = true }
serde_json = { workspace = true }
generational-box = { workspace = true }
futures-util = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["rt"] }
parking_lot = { workspace = true }

[features]
web = []
server = []

[dev-dependencies]
dioxus-fullstack = { workspace = true }
dioxus = { workspace = true, features = ["fullstack"] }

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
