[package]
name = "dioxus-fullstack-hooks"
authors = ["Jonathan Kelley", "Evan Almloff"]
version = { workspace = true }
edition = "2021"
description = "Hooks for serializing futures, values in dioxus-fullstack and other utilities"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["web", "gui", "server"]
resolver = "2"

[dependencies]
dioxus-core = { workspace = true }
dioxus-signals = { workspace = true }
dioxus-hooks = { workspace = true }
dioxus-fullstack-protocol = { workspace = true }
futures-channel = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
dioxus-fullstack = { workspace = true }
dioxus-lib = { workspace = true }
dioxus = { workspace = true }

[features]
web = []
server = []

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
