[package]
name = "manganis-core"
edition = "2021"
version = { workspace = true }
authors = ["Jonathan Kelley"]
description = "core for manganis"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/tree/main/packages/manganis/manganis-core"
homepage = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "assets"]
readme = "../manganis/README.md"

# be careful with dependencies you add here - these need to get compiled for the proc macro and therefore
# prevent the main code from compiling!
[dependencies]
serde = { workspace = true, features = ["derive"] }
const-serialize-08 = { package = "const-serialize", path = "../../const-serialize", version = "0.8.0-alpha.0", features = ["serde", "const-serialize-07"] }
const-serialize-07 = { package = "const-serialize", version = "=0.7.2" }
dioxus-core-types = { workspace = true, optional = true }
dioxus-cli-config = { workspace = true, optional = true }
winnow = { workspace = true }

[dev-dependencies]
manganis = { workspace = true }

[features]
dioxus = ["dep:dioxus-core-types", "dep:dioxus-cli-config"]
