[package]
name = "manganis-cli-support"
version.workspace = true
edition = "2021"
authors = ["Evan Almloff"]
description = "Ergonomic, automatic, cross crate asset collection and optimization"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/manganis/"
homepage = "https://dioxuslabs.com"
keywords = ["assets"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
manganis-common = { workspace = true }

serde = { version = "1.0.183", features = ["derive"] }
serde_json = {version="1.0.116"}
anyhow = "1"
rayon = "1.7.0"
rustc-hash = "1.1.0"

# Tailwind
railwind = "0.1.5"

# Image compression/conversion
# JPEG
mozjpeg = { version = "0.10.7", default-features = false, features = ["parallel"] }
# PNG
imagequant = "4.2.0"
png = "0.17.9"
# Conversion
image = { version = "0.25" }
ravif = { version = "0.11", default-features = false }

# CSS Minification
lightningcss = "1.0.0-alpha.44"

# Js minification
swc = "=0.283.0"
swc_common = "=0.37.1"

# Remote assets
url = { version = "2.4.0", features = ["serde"] }
reqwest = { version = "0.12.5", features = ["blocking"] }
tracing = "0.1.37"

# Extracting data from an executable
object = {version="0.36.0", features=["wasm"]}

[dev-dependencies]
tracing-subscriber = "0.3.18"

[features]
default = ["html"]
html = ["manganis-common/html"]

asm = ["ravif/asm", "mozjpeg/nasm_simd"]

# Note: this feature now enables nothing and should be removed in the next major version
webp = []
avif = []
