[package]
name = "const-serialize"
version = "0.8.0-alpha.0"
authors = ["Evan Almloff"]
edition = "2021"
description = "A serialization framework that works in const contexts"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dioxuslabs/dioxus"
homepage = "https://dioxuslabs.com/learn/0.5/getting_started"
keywords = ["const", "serialize"]
rust-version = "1.83.0"

[dependencies]
const-serialize-macro = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
const-serialize-07 = { package = "const-serialize", version = "=0.7.2", optional = true }

[dev-dependencies]
rand = { workspace = true }

[features]
test-big-endian = []
serde = ["dep:serde"]
# Enables serialization of the ConstStr with the older const-serialize-0.7 crate
const-serialize-07 = ["dep:const-serialize-07"]
