# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "native-headless-in-bevy"
version = "0.0.0"
edition = "2021"
license = "MIT"
publish = false

[features]
tracing = ["dep:tracing-subscriber", "dioxus-native-dom/tracing"]

[dependencies]
dioxus = { workspace = true }
dioxus-native-dom = { workspace = true }
blitz-dom = { workspace = true, default-features = true }
blitz-paint = { workspace = true, default-features = true }
blitz-traits = { workspace = true, default-features = true }
anyrender_vello = { workspace = true }
wgpu = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
bevy = { workspace = true }
vello = { workspace = true }
async-std = "1.13"
crossbeam-channel = "0.5"
paste = "1.0"
rustc-hash = "1"

