[package]
name = "dioxus-config-macro"
version = { workspace = true }
authors = ["Jonathan Kelley"]
edition = "2021"
description = "Configuration macros for Dioxus"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["web", "desktop", "mobile", "gui", "wasm"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }

[features]
default = []
fullstack = []
desktop = []
native = []
mobile = []
web = []
ssr = []
liveview = []

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
