[package]
name = "dioxus-cli-telemetry"
edition = "2021"
version.workspace = true
description = "Wire format for the dioxus CLI telemetry type"

[dependencies]
serde = { workspace = true, features = ["derive"] }
chrono = { workspace = true, features = ["serde"] }
rand.workspace = true
