[package]
name = "dioxus-devtools"
authors = ["Jonathan Kelley", "Evan Almloff"]
version = { workspace = true }
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com/learn/0.4/migration/hot_reload"
description = "Hot reloading utilities for Dioxus"
keywords = ["dom", "ui", "gui", "react", "hot-reloading"]

[dependencies]
dioxus-signals = { workspace = true }
dioxus-core = { workspace = true, features = ["serialize"] }
dioxus-devtools-types = { workspace = true }
dioxus-cli-config = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
subsecond = { workspace = true }
thiserror = { workspace = true }

futures-util = { workspace = true, features = ["sink", "async-await-macro"], optional = true }
futures-channel = { workspace = true, optional = true }

# hot reloading serve
tracing = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tungstenite = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
serde_json = { workspace = true }

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

[features]
default = []
serve = ["dep:futures-util", "dep:futures-channel"]
