[application]

# App name
name = "project_name"

# `build` & `serve` output path
out_dir = "dist"

# Static files copied verbatim into the built app (set to enable, e.g. "public")
public_dir = "public"

[web.app]

# HTML title tag content
title = "project_name"

[web.watcher]

# When watcher is triggered, regenerate the `index.html`
reload_html = true

# Which files or dirs will be monitored
watch_path = ["src", "public"]

[[web.proxy]]
backend = "http://localhost:8000/api/"
