[application]

# dioxus project name
name = "{{project-name}}"

# default platfrom
# you can also use `dioxus serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "{{default-platform}}"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "dioxus | â›º"

[web.watcher]

watch_path = ["src"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[web.tools]
