[package]
name = "dioxus-native"
version = { workspace = true }
authors = ["Jonathan Kelley", "Nico Burns"]
edition = "2021"
description = "Native renderer for Dioxus based on blitz"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com/learn/0.7/getting_started"
keywords = ["dom", "ui", "gui", "react"]

[features]
default = ["accessibility", "hot-reload", "net", "html", "svg", "system-fonts", "clipboard", "file_dialog"]
clipboard = ["blitz-shell/clipboard"]
file_dialog = ["blitz-shell/file_dialog"]
svg = ["blitz-dom/svg", "blitz-paint/svg"]
net = ["dep:tokio", "dep:blitz-net"]
html = ["dep:blitz-html"]
accessibility = ["blitz-shell/accessibility", "blitz-dom/accessibility"]
tracing = ["dep:tracing", "dioxus-native-dom/tracing", "blitz-shell/tracing", "blitz-dom/tracing"]
hot-reload = ["dep:dioxus-cli-config", "dep:dioxus-devtools"]
system-fonts = ["blitz-dom/system_fonts"]
autofocus = []

[dependencies]
# Blitz dependencies
anyrender = { workspace = true }
anyrender_vello = { workspace = true }
blitz-dom = { workspace = true }
blitz-html = { workspace = true, optional = true }
blitz-net = { workspace = true, optional = true }
blitz-paint = { workspace = true, optional = true }
blitz-traits = { workspace = true }
blitz-shell = { workspace = true }

# DioxusLabs dependencies
dioxus-core = { workspace = true }
dioxus-html = { workspace = true }
dioxus-native-dom = { workspace = true }
dioxus-asset-resolver = { workspace = true, features = ["native"] }
dioxus-cli-config = { workspace = true, optional = true }
dioxus-devtools = { workspace = true, optional = true }
dioxus-history = { workspace = true }
dioxus-document = { workspace = true }

# Windowing & Input
winit = { workspace = true }
keyboard-types = { workspace = true }

# IO & Networking
tokio = { workspace = true, features = ["rt-multi-thread"], optional = true }
webbrowser = { workspace = true }

# Other dependencies
tracing = { workspace = true, optional = true }
rustc-hash = { workspace = true }
futures-util = { workspace = true }

[package.metadata.docs.rs]
all-features = true
