[package]
name = "html-validation"
version = "0.1.2"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
description = "Validation for HTML elements and attributes"
keywords = ["html", "validation", "valid", "dom", "virtual"]
license = "MIT/Apache-2.0"
repository = "https://github.com/chinedufn/percy"
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
