[package]
name = "dx-macro-helpers"
version.workspace = true
edition = "2021"
authors = ["DioxusLabs"]
description = "Shared macro helpers for linker-based binary embedding"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus"
homepage = "https://dioxuslabs.com"

[lib]
proc-macro = false

[dependencies]
const-serialize = { workspace = true }
const-serialize-07 = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
