name: docs stable

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: docs
    steps:

      # NOTE: Comment out when https://github.com/rust-lang/mdBook/pull/1306 is merged and released
      # - name: Setup mdBook
      #   uses: peaceiris/actions-mdbook@v1
      #   with:
      #     mdbook-version: "0.4.10"

      # NOTE: Delete when the previous one is enabled
      - name: Setup mdBook
        run: |
          cargo install mdbook --git https://github.com/Demonthos/mdBook.git --branch master
      - uses: actions/checkout@v4

      - name: Build
        run: cd docs &&
          cd guide && mdbook build -d ../nightly/guide && cd .. &&
          cd router && mdbook build -d ../nightly/router && cd ..
          # cd reference && mdbook build -d ../nightly/reference && cd .. &&
          # cd fermi && mdbook build -d ../nightly/fermi && cd ..

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/nightly # The folder the action should deploy.
          target-folder: docs
          repository-name: dioxuslabs/docsite
          clean: false
          token: ${{ secrets.DEPLOY_KEY }} # let's pretend I don't need it for now
