[package]
name = "dioxus-interpreter-js"
version = { workspace = true }
edition = "2021"
authors = ["Jonathan Kelley"]
description = "JS Interpreter for Dioxus - a concurrent renderer-agnostic Virtual DOM for interactive user experiences"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
documentation = "https://docs.rs/dioxus"
keywords = ["dom", "ui", "gui", "react", "wasm"]

[dependencies]
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
js-sys = { version = "0.3.56", optional = true }
web-sys = { version = "0.3.56", optional = true, features = [
    "Element",
    "Node",
] }
sledgehammer_bindgen = { version = "0.5.0", default-features = false, optional = true }
sledgehammer_utils = { version = "0.2", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

dioxus-core = { workspace = true, optional = true }
dioxus-html = { workspace = true, optional = true }

[build-dependencies]
lazy-js-bundle = { workspace = true }

[features]
default = []
serialize = ["dep:serde"]
sledgehammer = ["dep:sledgehammer_bindgen", "dep:sledgehammer_utils"]
webonly = [
    "sledgehammer",
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
    "dep:js-sys",
    "dep:web-sys",
    "sledgehammer_bindgen/web",
]
binary-protocol = ["sledgehammer", "dep:dioxus-core", "dep:dioxus-html"]
minimal_bindings = []
